In [1]:
# Importing Packages
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn import datasets

The Iris dataset has 150 observations or Rows and 5 atttibutes or Columns of Iris Flowers.

First four columns are - **Sepal Length, Sepal Width , Petal Length, Petal Width**, all are in cm.


---


The Last column is containing the Classes - **['setosa' 'versicolor' 'virginica']**


---


As we are loading the dataset from sklearn, the dataset is already pre-processed.

**So, the Classes are - [ 0 , 1 , 2 ] instead of ['setosa' 'versicolor' 'virginica'].**

In [2]:
# Loading Dataset
data = datasets.load_iris()
print(data)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [3]:
x = data.data
y = data.target
z = data.target_names
print(data.feature_names)
print(x[0])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[5.1 3.5 1.4 0.2]


In [4]:
# Split Dataset
from sklearn.model_selection import train_test_split
x_train, x_test,  y_train, y_test = train_test_split(x, y, test_size=0.3)

In [5]:
# Data Shape
print(x_train.shape)
print(x_test.shape)

(105, 4)
(45, 4)


In [6]:
# Building the Model
model= Sequential()
model.add(Dense(100,input_shape=(4,), activation="relu"))
model.add(Dense(3, activation='softmax'))

In [7]:
# Compile the Model
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [8]:
# Fit the Model
model.fit(x_train,y_train, epochs=20)

Epoch 1/20
4/4 [==============================] - 1s 10ms/step - loss: 0.9917 - accuracy: 0.4095
Epoch 2/20
4/4 [==============================] - 0s 6ms/step - loss: 0.9423 - accuracy: 0.7810
Epoch 3/20
4/4 [==============================] - 0s 5ms/step - loss: 0.9072 - accuracy: 0.7714
Epoch 4/20
4/4 [==============================] - 0s 6ms/step - loss: 0.8697 - accuracy: 0.9048
Epoch 5/20
4/4 [==============================] - 0s 4ms/step - loss: 0.8353 - accuracy: 0.7810
Epoch 6/20
4/4 [==============================] - 0s 4ms/step - loss: 0.8019 - accuracy: 0.7429
Epoch 7/20
4/4 [==============================] - 0s 5ms/step - loss: 0.7747 - accuracy: 0.8381
Epoch 8/20
4/4 [==============================] - 0s 5ms/step - loss: 0.7476 - accuracy: 0.8190
Epoch 9/20
4/4 [==============================] - 0s 4ms/step - loss: 0.7226 - accuracy: 0.8095
Epoch 10/20
4/4 [==============================] - 0s 4ms/step - loss: 0.7004 - accuracy: 0.7143
Epoch 11/20
4/4 [=====================

In [9]:
# Evaluate the Model
model.evaluate(x_test, y_test)

2/2 [==============================] - 0s 8ms/step - loss: 0.5016 - accuracy: 0.7778


[0.5015564560890198, 0.7777777910232544]

In [10]:
# Predict for the first 10 Observations
pred=model.predict(x_test[:10])
print(pred)

1/1 [==============================] - 0s 86ms/step
[[0.83621085 0.11872709 0.04506197]
 [0.7644006  0.16224176 0.07335765]
 [0.03567742 0.28349593 0.6808266 ]
 [0.08332068 0.44679755 0.46988168]
 [0.13393469 0.43999785 0.42606738]
 [0.02927359 0.31524938 0.6554771 ]
 [0.82653904 0.12113537 0.05232553]
 [0.13265224 0.41106576 0.45628202]
 [0.07279955 0.36342126 0.56377923]
 [0.7789432  0.15289456 0.06816225]]


In [11]:
p=np.argmax(pred, axis=1)
print(p)
print(y_test[:10])

[0 0 2 2 1 2 0 2 2 0]
[0 0 2 1 1 2 0 1 2 0]


In [12]:
# Prediction Result
for i in p:
  print("Predicted-Class: {},   Name: {}".format(i,z[i]))

Predicted-Class: 0,   Name: setosa
Predicted-Class: 0,   Name: setosa
Predicted-Class: 2,   Name: virginica
Predicted-Class: 2,   Name: virginica
Predicted-Class: 1,   Name: versicolor
Predicted-Class: 2,   Name: virginica
Predicted-Class: 0,   Name: setosa
Predicted-Class: 2,   Name: virginica
Predicted-Class: 2,   Name: virginica
Predicted-Class: 0,   Name: setosa
